# Generated by Django 2.2.10 on 2020-02-27 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
