# Generated by Django 2.2.10 on 2020-03-02 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200227_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
