# Generated by Django 2.2.10 on 2020-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200302_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='flag',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='latitud',
            field=models.CharField(default='11.187949', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='longitud',
            field=models.CharField(default='-74.2311288', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatura',
            name='unidad',
            field=models.CharField(default='°C', max_length=10),
            preserve_default=False,
        ),
    ]
