# Generated by Django 2.2.10 on 2020-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chequeo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequeo',
            name='chequeado',
        ),
        migrations.AddField(
            model_name='chequeo',
            name='importancia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
