# Generated by Django 2.2.10 on 2020-05-15 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200515_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
        ),
    ]
