# Generated by Django 2.2.10 on 2020-05-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200515_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chequeo',
        ),
    ]
