# Generated by Django 2.2.10 on 2020-05-15 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_chequeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elemento', models.CharField(max_length=500)),
                ('importancia', models.IntegerField()),
                ('tiempo', models.IntegerField()),
                ('fecha', models.CharField(default=django.utils.timezone.now, max_length=300)),
            ],
        ),
    ]
