# Generated by Django 2.2.10 on 2020-05-29 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chequeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('humedad', models.FloatField()),
                ('fecha', models.CharField(default=django.utils.timezone.now, max_length=200)),
                ('unidad', models.CharField(max_length=10)),
                ('flag', models.IntegerField()),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
            ],
        ),
    ]
