# Generated by Django 2.2.10 on 2020-06-01 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_humedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable_nombre', models.CharField(max_length=100)),
                ('variable_codigo', models.IntegerField()),
                ('variable_valor', models.FloatField()),
                ('fecha', models.CharField(default=django.utils.timezone.now, max_length=200)),
                ('unidad', models.CharField(max_length=10)),
                ('flag', models.IntegerField()),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
            ],
        ),
    ]
