# Generated by Django 2.2.10 on 2020-06-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sensores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='fecha',
            field=models.CharField(default='2020-6-8 18:7:46', max_length=200),
        ),
    ]
