# Generated by Django 2.2.10 on 2020-06-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200608_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeo',
            name='fecha',
            field=models.CharField(default='2020-6-8 18:9:22', max_length=300),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='fecha',
            field=models.CharField(default='2020-6-8 18:9:22', max_length=200),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='fecha',
            field=models.CharField(default='2020-6-8 18:9:22', max_length=200),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='fecha',
            field=models.CharField(default='2020-6-8 18:9:22', max_length=200),
        ),
    ]
